{% set name = "PyMUMPS" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: dfa9471f045f03aad133c60d4aaeffb211b568e85940fa5d44556adcaefbd76c

build:
  number: 0
  script: |
    pip install . -vv --global-option="build_ext" \
       --global-option="-I$PREFIX/include" \
       --global-option="-L$PREFIX/lib"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - python
    - mumps-mpi
    - mumps-include
    - setuptools
    - mpi4py
    - pip
  run:
    - python
    - scipy
    - setuptools
    - mumps-mpi
    - mpi4py

test:
  imports:
    - mumps

about:
  home: https://github.com/PyMUMPS/pymumps.git
  license: BSD-3-Clause
  license_file: COPYING
  summary: 'PyMUMPS: Python parallel sparse direct solver'

extra:
  recipe-maintainers:
    - santiagoropb
    - sdrave
