travis:
  secure:
    BINSTAR_TOKEN: k1Fhkqw7KV1Uvnn/kHG+nAmgFJQHHjaBimfTJ5PitHz+fgldvisfFbubhaGjFkuvIZOcwow0LOFecYdKwRp5JbHS0RXbUMuRHOCANyCcHPh54bNmPa0Wfz42/RDShOl7CcUANOgVLjR5HeH1Vom2NzR1u3KoL0/HRKeyqN2Rxjcr29Sl2/xYZv2qrXJq5Pw0jwHi+l+kKfahdA0YaDpZGLyQM4X/icyOwEd02yYKjfOc6ekt6Cm4y/QX9WkDoXUlOo1pdXqohjuZ8xSrhv1caAnegUZ6hU1+MxR2PyM4eO/ygcp5lVQqVdXugH17IiffM2UtHRxRMtOwSBGICilowXHPtOrC3tx/DB2WLgWd8UL0Z4AEB26vUsl8qn2omN3Qa8OyNfiXTuyc2l+quFuau+CjhJ1/2V9LRAYlhe7UdxofNNRfQ5M3OIPWTmH00YangKhuMG5LWrgIJwNFkPU7d1gquiUL6vutWXg54PQs1ebFYu+lTytbRbiADMujBsoSXG6qG/zAtm1LVSyEUJi/RY+eLraXui1xwTXs9wpnv5g6ynuo7HQDZS1gLdP2GLV7jHoZV60vF0LPZunDwendcRbB5Cs0AOHKAsuVH8hz4MJwFuNnzASJ/CQxfaQ8nVQikfPTfyH3vmKmfToXBvqu8B2uouf2GBAArsE1KLlkYCA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
